version: 0.2

phases:
  install:
  commands:
    - echo "Installing Terraform..."
    - mkdir -p /tmp/terraform-install
    - curl -fsSL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.15.8/terraform_1.15.8_linux_amd64.zip
    - unzip -o /tmp/terraform.zip -d /tmp/terraform-install
    - mv /tmp/terraform-install/terraform /usr/local/bin/terraform
    - terraform version

  pre_build:
    commands:
      - cd "$CODEBUILD_SRC_DIR/terraform/environments/dev"
      - aws sts get-caller-identity
      - terraform init -input=false
      - cp "$CODEBUILD_SRC_DIR_TerraformPlanArtifact/tfplan" ./tfplan

  build:
    commands:
      - terraform apply -input=false tfplan