#!/bin/bash
set -e

APP_DIR="/opt/preordering-backend"
IMAGE_FILE="$APP_DIR/deployment/image.json"
AWS_REGION="us-west-2"
AWS_ACCOUNT_ID="395063533284"
ECR_REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

echo "========== INSTALLING NEW IMAGE =========="

# Ensure the image metadata file exists
if [ ! -f "$IMAGE_FILE" ]; then
  echo "ERROR: $IMAGE_FILE was not found."
  exit 1
fi

# Read the exact image URI generated by CodeBuild
IMAGE_URI=$(python3 -c "
import json
with open('$IMAGE_FILE', 'r') as file:
    print(json.load(file)['imageUri'])
")

if [ -z "$IMAGE_URI" ]; then
  echo "ERROR: imageUri is empty."
  exit 1
fi

echo "Deploying image: $IMAGE_URI"

# Authenticate Docker with Amazon ECR using the EC2 IAM role
aws ecr get-login-password \
  --region "$AWS_REGION" |
  sudo docker login \
    --username AWS \
    --password-stdin "$ECR_REGISTRY"

# Pull the exact commit-tagged image
sudo docker pull "$IMAGE_URI"

echo "Docker image pulled successfully."